package morecolors;

/**
 *
 * @author Bakmie
 */
public class ColorForm extends javax.swing.JFrame {

    /**
     * Creates new form ColorForm
     */
    public ColorForm() {
        initComponents();
        
        // did it work?

        res_pic1.setLocation(220, 420);
        res_pic2.setLocation(220, 80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorTriangles2 = new colortriangles.colorTriangles();
        colors1 = new colors.Colors();
        colorTrianglesR1 = new colortriangles.colorTrianglesR();
        button_swap = new javax.swing.JButton();
        res_pic1 = new javax.swing.JLabel();
        res_pic2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_swap.setText("Swap");
        button_swap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_swapActionPerformed(evt);
                button_swapActionPerformed1(evt);
                button_swapActionPerformed2(evt);
                button_swapActionPerformed3(evt);
            }
        });

        res_pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/morecolors/noodles.png"))); // NOI18N
        res_pic1.setMaximumSize(new java.awt.Dimension(2775, 1536));
        res_pic1.setMinimumSize(new java.awt.Dimension(2775, 1536));

        res_pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/morecolors/ren.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_swap)
                        .addGap(0, 456, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(colorTriangles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(res_pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(colors1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(colorTrianglesR1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(res_pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(colorTriangles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_swap)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(res_pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorTrianglesR1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colors1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(res_pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_swapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_swapActionPerformed
        // TODO add your handling code here:
        
        colors1.change();
        colorTriangles2.change();
        colorTrianglesR1.change();
        
        int p1x = res_pic1.getX();
        int p1y = res_pic1.getY();
        
        int p2x = res_pic2.getX();
        int p2y = res_pic2.getY();
        
        if (p1y == 390 && p2y == 60 ){
            res_pic1.setLocation(210, 60);
            res_pic2.setLocation(210, 390);
        } else {
            res_pic1.setLocation(210, 390);
            res_pic2.setLocation(210, 60);
        }

    }//GEN-LAST:event_button_swapActionPerformed

    private void button_swapActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_swapActionPerformed1
        colors1.change();
    }//GEN-LAST:event_button_swapActionPerformed1

    private void button_swapActionPerformed2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_swapActionPerformed2
        colorTriangles2.change();
    }//GEN-LAST:event_button_swapActionPerformed2

    private void button_swapActionPerformed3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_swapActionPerformed3
        colorTriangles2.change();
    }//GEN-LAST:event_button_swapActionPerformed3

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_swap;
    private colortriangles.colorTriangles colorTriangles2;
    private colortriangles.colorTrianglesR colorTrianglesR1;
    private colors.Colors colors1;
    private javax.swing.JLabel res_pic1;
    private javax.swing.JLabel res_pic2;
    // End of variables declaration//GEN-END:variables
}
